version: '3.8'
services:
    
 mongo-server:
  image: mongo
  restart: always
  container_name: mongo-server
  hostname: mongo-server
  environment:
   MONGO_INITDB_ROOT_USERNAME: mongo
   MONGO_INITDB_ROOT_PASSWORD: mongo
  volumes:
   - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  ports:
   - 27017:27017
   
 mysql-server:
  image: mysql
  restart: always
  container_name: mysql-server
  hostname: mysql-server
  environment:
   MYSQL_USER: ubs
   MYSQL_PASSWORD: ubs
   MYSQL_ROOT_PASSWORD: ubs
   MYSQL_DATABASE: ubs
  ports:
   - 3306:3306
