version: '3.8'
services:
 mongo-server:
  image: mongo
  restart: always
  container_name: mongo-server
  hostname: mongo-server
  environment:
   MONGO_INITDB_ROOT_USERNAME: mongo
   MONGO_INITDB_ROOT_PASSWORD: mongo
  volumes:
   - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  ports:
   - 27017:27017
